version: '3.9'
services:
  web:
    build: .
    ports:
      - '5000:5000'
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
    volumes:
      - /home/ec2-user/loaderToken/loaderio-74510e8b027a788a796be3623147197b.txt:/loaderToken/loaderio-74510e8b027a788a796be3623147197b.txt
    restart: always


  db:
    build: ./db-config
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3318:3306
    volumes:
      - /var/lib/mysql-files:/var/lib/mysql-files
      - /etc/my.cnf:/etc/mysql/conf.d